{
 "title": "MySQL Replication Status",
 "time": { "from": "+053716-11-17T05:16:47.855Z", "to": "+056588-08-04T02:28:10.735Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Replication Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mysql_slave_status_slave_io_running == 1) and (mysql_slave_status_slave_sql_running == 1)"
    }
   ]
  },
  {
   "title": "IO Thread Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "SQL Thread Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  },
  {
   "title": "Replication Thread History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "IO Thread"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "SQL Thread"
    }
   ]
  }
 ]
}